# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
repository: "genaralskar/genaralskar.github.io"

title: Collin Anderson
email: CollinAnderson827@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: genaralskar
github_username: genaralskar
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Collin Anderson"
  avatar : "/assets/images/headshotSquare.jpg"
  bio    : "I love playing games, making games, and all sorts of nerd stuff!"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/genaralskar"
    - label: "itch.io"
      icon: "fab fa-itch-io"
      url: "https://genaralskar.itch.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/genaralskar"
    - label: "Artstation"
      icon: "fab fa-fw fa-artstation"
      url: "https://artstation.com/genaralskar"
    - label: "Back to top"
      icon: "fas fa-arrow-circle-up"
      url: "#"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/genaralskar"
    - label: "itch.io"
      icon: "fab fa-itch-io"
      url: "https://genaralskar.itch.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/genaralskar"
    - label: "Artstation"
      icon: "fab fa-fw fa-artstation"
      url: "https://artstation.com/genaralskar"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

logo: "/assets/images/logo.png"
masthead_title: "genaralskar"
search: true

twitter:
  username: "genaralskar"

og_image: /assets/images/logo.png

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/genaralskar"
    - "https://www.linkedin.com/in/collin-anderson-1a216086/"

